export const DATA_LOADING = 'DATA_LOADING';
export const DATA_FAIL = 'DATA_FAIL';
export const DATA_SUCCESS = 'DATA_SUCCESS';

export const CREATE_LOADING = 'CREATE_LOADING';
export const CREATE_FAIL = 'CREATE_FAIL';
export const CREATE_SUCCESS = 'CREATE_SUCCESS';

export const GET_DATA_LOADING = 'GET_DATA_LOADING';
export const GET_DATA_FAIL = 'GET_DATA_FAIL';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';

export const GET_DATA_BYID_LOADING = 'GET_DATA_BYID_LOADING';
export const GET_DATA_BYID_FAIL = 'GET_DATA_BYID_FAIL';
export const GET_DATA_BYID_SUCCESS = 'GET_DATA_BYID_SUCCESS';
